version: "3.8"

services:
  backend:
    build: ./backend
    container_name: diabetes-backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: diabetes-frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend
